---
  - name: install apache2 ubuntu
    become: yes
    tasks:
      - name: Install apache 
        ansible.builtin.apt:
          name: apache2
          state: present
          update_cache: yes
      - name: php libapache2-mod-php php-mysql
        ansible.builtin.apt:
          name: php libapache2-mod-php php-mysql
          update_cache: yes
          state: present